"""Initial Migration

Revision ID: 511d0f9cb8a6
Revises: 
Create Date: 2025-09-23 07:15:03.145711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511d0f9cb8a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=256), nullable=True),
    sa.Column('api_key_plain_encrypted', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('api_key_approved', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_encrypted'),
    sa.UniqueConstraint('email')
    )
    op.create_table('email_bot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email_encrypted', sa.String(length=256), nullable=False),
    sa.Column('password_encrypted', sa.String(length=256), nullable=False),
    sa.Column('smtp_server', sa.String(length=128), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('email_bot')
    op.drop_table('user')
    # ### end Alembic commands ###
