"""inital migration

Revision ID: d254d2fe361f
Revises: 
Create Date: 2025-09-22 17:20:59.444273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd254d2fe361f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=256), nullable=True),
    sa.Column('api_key_plain_encrypted', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('api_key_approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_encrypted'),
    sa.UniqueConstraint('email')
    )
    op.create_table('email_bot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email_encrypted', sa.String(length=256), nullable=False),
    sa.Column('password_encrypted', sa.String(length=256), nullable=False),
    sa.Column('smtp_server', sa.String(length=128), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_bot')
    op.drop_table('user')
    # ### end Alembic commands ###
